# Generated by Django 4.1.4 on 2023-03-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_malwarefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='exifImages/')),
                ('case_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='user.case')),
            ],
        ),
    ]
