# Generated by Django 4.1.4 on 2023-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_casesearchmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseSearchModel',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='case_obj',
        ),
        migrations.RemoveField(
            model_name='malwarefile',
            name='case_obj',
        ),
        migrations.AddField(
            model_name='malwarefile',
            name='case_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
